// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module snn_mnist_hls_lif_layer_10_128_stream_ap_uint_10_0_stream_ap_uint_10_0_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out1_dout,
        out1_empty_n,
        out1_read,
        out2_din,
        out2_full_n,
        out2_write
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] out1_dout;
input   out1_empty_n;
output   out1_read;
output  [9:0] out2_din;
input   out2_full_n;
output   out2_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out1_read;
reg[9:0] out2_din;
reg out2_write;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;
reg    out2_blk_n;
wire    ap_CS_fsm_state2;
reg   [0:0] icmp_ln51_reg_1295;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln51_128_reg_1310;
wire    ap_CS_fsm_state4;
reg   [0:0] icmp_ln51_129_reg_1325;
wire    ap_CS_fsm_state5;
reg   [0:0] icmp_ln51_130_reg_1340;
wire    ap_CS_fsm_state6;
reg   [0:0] icmp_ln51_131_reg_1355;
wire    ap_CS_fsm_state7;
reg   [0:0] icmp_ln51_132_reg_1370;
wire    ap_CS_fsm_state8;
reg   [0:0] icmp_ln51_133_reg_1385;
wire    ap_CS_fsm_state9;
reg   [0:0] icmp_ln51_134_reg_1400;
wire    ap_CS_fsm_state10;
reg   [0:0] icmp_ln51_135_reg_1415;
wire    ap_CS_fsm_state11;
reg   [0:0] icmp_ln51_136_reg_1430;
wire   [0:0] icmp_ln51_fu_319_p2;
reg   [7:0] trunc_ln_reg_1300;
reg   [0:0] tmp_386_reg_1305;
wire   [0:0] icmp_ln51_128_fu_379_p2;
reg   [7:0] trunc_ln56_s_reg_1315;
reg   [0:0] tmp_389_reg_1320;
wire   [0:0] icmp_ln51_129_fu_439_p2;
reg   [7:0] trunc_ln56_127_reg_1330;
reg   [0:0] tmp_392_reg_1335;
wire   [0:0] icmp_ln51_130_fu_499_p2;
reg   [7:0] trunc_ln56_128_reg_1345;
reg   [0:0] tmp_395_reg_1350;
wire   [0:0] icmp_ln51_131_fu_559_p2;
reg   [7:0] trunc_ln56_129_reg_1360;
reg   [0:0] tmp_398_reg_1365;
wire   [0:0] icmp_ln51_132_fu_619_p2;
reg   [7:0] trunc_ln56_130_reg_1375;
reg   [0:0] tmp_401_reg_1380;
wire   [0:0] icmp_ln51_133_fu_679_p2;
reg   [7:0] trunc_ln56_131_reg_1390;
reg   [0:0] tmp_404_reg_1395;
wire   [0:0] icmp_ln51_134_fu_739_p2;
reg   [7:0] trunc_ln56_132_reg_1405;
reg   [0:0] tmp_407_reg_1410;
wire   [0:0] icmp_ln51_135_fu_799_p2;
reg   [7:0] trunc_ln56_133_reg_1420;
reg   [0:0] tmp_410_reg_1425;
wire   [0:0] icmp_ln51_136_fu_859_p2;
reg   [7:0] trunc_ln56_134_reg_1435;
reg   [0:0] tmp_413_reg_1440;
wire  signed [8:0] p_promoted_fu_917_p3;
reg   [8:0] p_promoted_reg_1445;
wire  signed [15:0] sext_ln51_fu_924_p1;
reg  signed [15:0] sext_ln51_reg_1450;
wire  signed [8:0] p_promoted6_fu_940_p3;
reg   [8:0] p_promoted6_reg_1455;
wire  signed [15:0] sext_ln51_127_fu_947_p1;
reg  signed [15:0] sext_ln51_127_reg_1460;
wire  signed [8:0] p_promoted8_fu_963_p3;
reg   [8:0] p_promoted8_reg_1465;
wire  signed [15:0] sext_ln51_128_fu_970_p1;
reg  signed [15:0] sext_ln51_128_reg_1470;
wire  signed [8:0] p_promoted10_fu_986_p3;
reg   [8:0] p_promoted10_reg_1475;
wire  signed [15:0] sext_ln51_129_fu_993_p1;
reg  signed [15:0] sext_ln51_129_reg_1480;
wire  signed [8:0] p_promoted12_fu_1009_p3;
reg   [8:0] p_promoted12_reg_1485;
wire  signed [15:0] sext_ln51_130_fu_1016_p1;
reg  signed [15:0] sext_ln51_130_reg_1490;
wire  signed [8:0] p_promoted14_fu_1032_p3;
reg   [8:0] p_promoted14_reg_1495;
wire  signed [15:0] sext_ln51_131_fu_1039_p1;
reg  signed [15:0] sext_ln51_131_reg_1500;
wire  signed [8:0] p_promoted16_fu_1055_p3;
reg   [8:0] p_promoted16_reg_1505;
wire  signed [15:0] sext_ln51_132_fu_1062_p1;
reg  signed [15:0] sext_ln51_132_reg_1510;
wire  signed [8:0] p_promoted18_fu_1078_p3;
reg   [8:0] p_promoted18_reg_1515;
wire  signed [15:0] sext_ln51_133_fu_1085_p1;
reg  signed [15:0] sext_ln51_133_reg_1520;
wire  signed [8:0] p_promoted20_fu_1101_p3;
reg   [8:0] p_promoted20_reg_1525;
wire  signed [15:0] sext_ln51_134_fu_1108_p1;
reg  signed [15:0] sext_ln51_134_reg_1530;
wire  signed [8:0] p_promoted22_fu_1124_p3;
reg   [8:0] p_promoted22_reg_1535;
wire  signed [15:0] sext_ln63_fu_1131_p1;
reg  signed [15:0] sext_ln63_reg_1540;
wire   [0:0] tmp_s_nbreadreq_fu_161_p3;
reg   [0:0] tmp_s_reg_1545;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_idle;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld;
wire   [15:0] grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out;
wire    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169;
reg    ap_block_state11;
wire    ap_CS_fsm_state14;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241;
reg   [15:0] ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4;
reg   [15:0] void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250;
reg    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [15:0] add_ln74_loc_fu_140;
reg   [15:0] add_ln74_128_loc_fu_136;
reg   [15:0] add_ln74_129_loc_fu_132;
reg   [15:0] add_ln74_130_loc_fu_128;
reg   [15:0] add_ln74_131_loc_fu_124;
reg   [15:0] add_ln74_132_loc_fu_120;
reg   [15:0] add_ln74_133_loc_fu_116;
reg   [15:0] add_ln74_134_loc_fu_112;
reg   [15:0] add_ln74_135_loc_fu_108;
reg   [15:0] add_ln74_136_loc_fu_104;
reg    ap_block_state2;
reg    ap_block_state3;
reg    ap_block_state4;
reg    ap_block_state5;
reg    ap_block_state6;
reg    ap_block_state7;
reg    ap_block_state8;
reg    ap_block_state9;
reg    ap_block_state10;
wire  signed [15:0] tmp_fu_309_p1;
wire   [5:0] tmp_fu_309_p4;
wire  signed [15:0] sext_ln56_fu_325_p0;
wire  signed [15:0] tmp_385_fu_329_p1;
wire   [21:0] tmp_385_fu_329_p3;
wire  signed [23:0] sext_ln56_384_fu_337_p1;
wire  signed [23:0] sext_ln56_fu_325_p1;
wire   [23:0] add_ln56_256_fu_341_p2;
wire  signed [15:0] tmp_387_fu_369_p1;
wire   [5:0] tmp_387_fu_369_p4;
wire  signed [15:0] sext_ln56_257_fu_385_p0;
wire  signed [15:0] tmp_388_fu_389_p1;
wire   [21:0] tmp_388_fu_389_p3;
wire  signed [23:0] sext_ln56_386_fu_397_p1;
wire  signed [23:0] sext_ln56_257_fu_385_p1;
wire   [23:0] add_ln56_257_fu_401_p2;
wire  signed [15:0] tmp_390_fu_429_p1;
wire   [5:0] tmp_390_fu_429_p4;
wire  signed [15:0] sext_ln56_259_fu_445_p0;
wire  signed [15:0] tmp_391_fu_449_p1;
wire   [21:0] tmp_391_fu_449_p3;
wire  signed [23:0] sext_ln56_388_fu_457_p1;
wire  signed [23:0] sext_ln56_259_fu_445_p1;
wire   [23:0] add_ln56_258_fu_461_p2;
wire  signed [15:0] tmp_393_fu_489_p1;
wire   [5:0] tmp_393_fu_489_p4;
wire  signed [15:0] sext_ln56_261_fu_505_p0;
wire  signed [15:0] tmp_394_fu_509_p1;
wire   [21:0] tmp_394_fu_509_p3;
wire  signed [23:0] sext_ln56_390_fu_517_p1;
wire  signed [23:0] sext_ln56_261_fu_505_p1;
wire   [23:0] add_ln56_259_fu_521_p2;
wire  signed [15:0] tmp_396_fu_549_p1;
wire   [5:0] tmp_396_fu_549_p4;
wire  signed [15:0] sext_ln56_263_fu_565_p0;
wire  signed [15:0] tmp_397_fu_569_p1;
wire   [21:0] tmp_397_fu_569_p3;
wire  signed [23:0] sext_ln56_392_fu_577_p1;
wire  signed [23:0] sext_ln56_263_fu_565_p1;
wire   [23:0] add_ln56_260_fu_581_p2;
wire  signed [15:0] tmp_399_fu_609_p1;
wire   [5:0] tmp_399_fu_609_p4;
wire  signed [15:0] sext_ln56_265_fu_625_p0;
wire  signed [15:0] tmp_400_fu_629_p1;
wire   [21:0] tmp_400_fu_629_p3;
wire  signed [23:0] sext_ln56_394_fu_637_p1;
wire  signed [23:0] sext_ln56_265_fu_625_p1;
wire   [23:0] add_ln56_261_fu_641_p2;
wire  signed [15:0] tmp_402_fu_669_p1;
wire   [5:0] tmp_402_fu_669_p4;
wire  signed [15:0] sext_ln56_267_fu_685_p0;
wire  signed [15:0] tmp_403_fu_689_p1;
wire   [21:0] tmp_403_fu_689_p3;
wire  signed [23:0] sext_ln56_396_fu_697_p1;
wire  signed [23:0] sext_ln56_267_fu_685_p1;
wire   [23:0] add_ln56_262_fu_701_p2;
wire  signed [15:0] tmp_405_fu_729_p1;
wire   [5:0] tmp_405_fu_729_p4;
wire  signed [15:0] sext_ln56_269_fu_745_p0;
wire  signed [15:0] tmp_406_fu_749_p1;
wire   [21:0] tmp_406_fu_749_p3;
wire  signed [23:0] sext_ln56_398_fu_757_p1;
wire  signed [23:0] sext_ln56_269_fu_745_p1;
wire   [23:0] add_ln56_263_fu_761_p2;
wire  signed [15:0] tmp_408_fu_789_p1;
wire   [5:0] tmp_408_fu_789_p4;
wire  signed [15:0] sext_ln56_271_fu_805_p0;
wire  signed [15:0] tmp_409_fu_809_p1;
wire   [21:0] tmp_409_fu_809_p3;
wire  signed [23:0] sext_ln56_400_fu_817_p1;
wire  signed [23:0] sext_ln56_271_fu_805_p1;
wire   [23:0] add_ln56_264_fu_821_p2;
wire  signed [15:0] tmp_411_fu_849_p1;
wire   [5:0] tmp_411_fu_849_p4;
wire  signed [15:0] sext_ln56_273_fu_865_p0;
wire  signed [15:0] tmp_412_fu_869_p1;
wire   [21:0] tmp_412_fu_869_p3;
wire  signed [23:0] sext_ln56_402_fu_877_p1;
wire  signed [23:0] sext_ln56_273_fu_865_p1;
wire   [23:0] add_ln56_265_fu_881_p2;
wire  signed [8:0] sext_ln56_385_fu_905_p1;
wire   [8:0] zext_ln56_fu_908_p1;
wire   [8:0] add_ln56_fu_911_p2;
wire  signed [8:0] sext_ln56_387_fu_928_p1;
wire   [8:0] zext_ln56_128_fu_931_p1;
wire   [8:0] add_ln56_128_fu_934_p2;
wire  signed [8:0] sext_ln56_389_fu_951_p1;
wire   [8:0] zext_ln56_129_fu_954_p1;
wire   [8:0] add_ln56_129_fu_957_p2;
wire  signed [8:0] sext_ln56_391_fu_974_p1;
wire   [8:0] zext_ln56_130_fu_977_p1;
wire   [8:0] add_ln56_130_fu_980_p2;
wire  signed [8:0] sext_ln56_393_fu_997_p1;
wire   [8:0] zext_ln56_131_fu_1000_p1;
wire   [8:0] add_ln56_131_fu_1003_p2;
wire  signed [8:0] sext_ln56_395_fu_1020_p1;
wire   [8:0] zext_ln56_132_fu_1023_p1;
wire   [8:0] add_ln56_132_fu_1026_p2;
wire  signed [8:0] sext_ln56_397_fu_1043_p1;
wire   [8:0] zext_ln56_133_fu_1046_p1;
wire   [8:0] add_ln56_133_fu_1049_p2;
wire  signed [8:0] sext_ln56_399_fu_1066_p1;
wire   [8:0] zext_ln56_134_fu_1069_p1;
wire   [8:0] add_ln56_134_fu_1072_p2;
wire  signed [8:0] sext_ln56_401_fu_1089_p1;
wire   [8:0] zext_ln56_135_fu_1092_p1;
wire   [8:0] add_ln56_135_fu_1095_p2;
wire  signed [8:0] sext_ln56_403_fu_1112_p1;
wire   [8:0] zext_ln56_136_fu_1115_p1;
wire   [8:0] add_ln56_136_fu_1118_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1 = 16'd0;
#0 void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials = 16'd0;
#0 grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg = 1'b0;
end

snn_mnist_hls_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start),
    .ap_done(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done),
    .ap_idle(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_idle),
    .ap_ready(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready),
    .p_promoted22(p_promoted22_reg_1535),
    .p_promoted20(p_promoted20_reg_1525),
    .p_promoted18(p_promoted18_reg_1515),
    .p_promoted16(p_promoted16_reg_1505),
    .p_promoted14(p_promoted14_reg_1495),
    .p_promoted12(p_promoted12_reg_1485),
    .p_promoted10(p_promoted10_reg_1475),
    .p_promoted8(p_promoted8_reg_1465),
    .p_promoted6(p_promoted6_reg_1455),
    .p_promoted(p_promoted_reg_1445),
    .out1_dout(out1_dout),
    .out1_empty_n(out1_empty_n),
    .out1_read(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read),
    .add_ln74_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out),
    .add_ln74_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld),
    .add_ln74_128_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out),
    .add_ln74_128_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld),
    .add_ln74_129_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out),
    .add_ln74_129_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld),
    .add_ln74_130_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out),
    .add_ln74_130_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld),
    .add_ln74_131_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out),
    .add_ln74_131_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld),
    .add_ln74_132_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out),
    .add_ln74_132_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld),
    .add_ln74_133_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out),
    .add_ln74_133_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld),
    .add_ln74_134_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out),
    .add_ln74_134_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld),
    .add_ln74_135_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out),
    .add_ln74_135_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld),
    .add_ln74_136_out(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out),
    .add_ln74_136_out_ap_vld(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= 1'b1;
        end else if ((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready == 1'b1)) begin
            grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178 <= add_ln74_128_loc_fu_136;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178 <= sext_ln51_127_reg_1460;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196 <= add_ln74_129_loc_fu_132;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196 <= sext_ln51_128_reg_1470;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205 <= add_ln74_130_loc_fu_128;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205 <= sext_ln51_129_reg_1480;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214 <= add_ln74_131_loc_fu_124;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214 <= sext_ln51_130_reg_1490;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223 <= add_ln74_132_loc_fu_120;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223 <= sext_ln51_131_reg_1500;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232 <= add_ln74_133_loc_fu_116;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232 <= sext_ln51_132_reg_1510;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241 <= add_ln74_134_loc_fu_112;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241 <= sext_ln51_133_reg_1520;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250 <= add_ln74_135_loc_fu_108;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250 <= sext_ln51_134_reg_1530;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187 <= add_ln74_136_loc_fu_104;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187 <= sext_ln63_reg_1540;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169 <= add_ln74_loc_fu_140;
    end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169 <= sext_ln51_reg_1450;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_128_loc_fu_136 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_129_loc_fu_132 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_130_loc_fu_128 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_131_loc_fu_124 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_132_loc_fu_120 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_133_loc_fu_116 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_134_loc_fu_112 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_135_loc_fu_108 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_136_loc_fu_104 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln74_loc_fu_140 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln51_128_reg_1310 <= icmp_ln51_128_fu_379_p2;
        icmp_ln51_129_reg_1325 <= icmp_ln51_129_fu_439_p2;
        icmp_ln51_130_reg_1340 <= icmp_ln51_130_fu_499_p2;
        icmp_ln51_131_reg_1355 <= icmp_ln51_131_fu_559_p2;
        icmp_ln51_132_reg_1370 <= icmp_ln51_132_fu_619_p2;
        icmp_ln51_133_reg_1385 <= icmp_ln51_133_fu_679_p2;
        icmp_ln51_134_reg_1400 <= icmp_ln51_134_fu_739_p2;
        icmp_ln51_135_reg_1415 <= icmp_ln51_135_fu_799_p2;
        icmp_ln51_136_reg_1430 <= icmp_ln51_136_fu_859_p2;
        icmp_ln51_reg_1295 <= icmp_ln51_fu_319_p2;
        tmp_386_reg_1305 <= add_ln56_256_fu_341_p2[32'd15];
        tmp_389_reg_1320 <= add_ln56_257_fu_401_p2[32'd15];
        tmp_392_reg_1335 <= add_ln56_258_fu_461_p2[32'd15];
        tmp_395_reg_1350 <= add_ln56_259_fu_521_p2[32'd15];
        tmp_398_reg_1365 <= add_ln56_260_fu_581_p2[32'd15];
        tmp_401_reg_1380 <= add_ln56_261_fu_641_p2[32'd15];
        tmp_404_reg_1395 <= add_ln56_262_fu_701_p2[32'd15];
        tmp_407_reg_1410 <= add_ln56_263_fu_761_p2[32'd15];
        tmp_410_reg_1425 <= add_ln56_264_fu_821_p2[32'd15];
        tmp_413_reg_1440 <= add_ln56_265_fu_881_p2[32'd15];
        trunc_ln56_127_reg_1330 <= {{add_ln56_258_fu_461_p2[23:16]}};
        trunc_ln56_128_reg_1345 <= {{add_ln56_259_fu_521_p2[23:16]}};
        trunc_ln56_129_reg_1360 <= {{add_ln56_260_fu_581_p2[23:16]}};
        trunc_ln56_130_reg_1375 <= {{add_ln56_261_fu_641_p2[23:16]}};
        trunc_ln56_131_reg_1390 <= {{add_ln56_262_fu_701_p2[23:16]}};
        trunc_ln56_132_reg_1405 <= {{add_ln56_263_fu_761_p2[23:16]}};
        trunc_ln56_133_reg_1420 <= {{add_ln56_264_fu_821_p2[23:16]}};
        trunc_ln56_134_reg_1435 <= {{add_ln56_265_fu_881_p2[23:16]}};
        trunc_ln56_s_reg_1315 <= {{add_ln56_257_fu_401_p2[23:16]}};
        trunc_ln_reg_1300 <= {{add_ln56_256_fu_341_p2[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_promoted10_reg_1475 <= p_promoted10_fu_986_p3;
        p_promoted12_reg_1485 <= p_promoted12_fu_1009_p3;
        p_promoted14_reg_1495 <= p_promoted14_fu_1032_p3;
        p_promoted16_reg_1505 <= p_promoted16_fu_1055_p3;
        p_promoted18_reg_1515 <= p_promoted18_fu_1078_p3;
        p_promoted20_reg_1525 <= p_promoted20_fu_1101_p3;
        p_promoted22_reg_1535 <= p_promoted22_fu_1124_p3;
        p_promoted6_reg_1455 <= p_promoted6_fu_940_p3;
        p_promoted8_reg_1465 <= p_promoted8_fu_963_p3;
        p_promoted_reg_1445 <= p_promoted_fu_917_p3;
        sext_ln51_127_reg_1460 <= sext_ln51_127_fu_947_p1;
        sext_ln51_128_reg_1470 <= sext_ln51_128_fu_970_p1;
        sext_ln51_129_reg_1480 <= sext_ln51_129_fu_993_p1;
        sext_ln51_130_reg_1490 <= sext_ln51_130_fu_1016_p1;
        sext_ln51_131_reg_1500 <= sext_ln51_131_fu_1039_p1;
        sext_ln51_132_reg_1510 <= sext_ln51_132_fu_1062_p1;
        sext_ln51_133_reg_1520 <= sext_ln51_133_fu_1085_p1;
        sext_ln51_134_reg_1530 <= sext_ln51_134_fu_1108_p1;
        sext_ln51_reg_1450 <= sext_ln51_fu_924_p1;
        sext_ln63_reg_1540 <= sext_ln63_fu_1131_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_s_reg_1545 <= tmp_s_nbreadreq_fu_161_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4;
        void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state11)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state7)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state8)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state9)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4 = add_ln74_128_loc_fu_136;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4 = add_ln74_129_loc_fu_132;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4 = add_ln74_130_loc_fu_128;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4 = add_ln74_131_loc_fu_124;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4 = add_ln74_132_loc_fu_120;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4 = add_ln74_133_loc_fu_116;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4 = add_ln74_134_loc_fu_112;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4 = add_ln74_135_loc_fu_108;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4 = add_ln74_136_loc_fu_104;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187;
    end
end

always @ (*) begin
    if (((tmp_s_reg_1545 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4 = add_ln74_loc_fu_140;
    end else begin
        ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4 = void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        out1_read = grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read;
    end else begin
        out1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln51_131_reg_1355 == 1'd1) & (1'b1 == ap_CS_fsm_state6)) | ((icmp_ln51_130_reg_1340 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln51_129_reg_1325 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln51_128_reg_1310 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln51_reg_1295 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state11) & (icmp_ln51_136_reg_1430 == 1'd1)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln51_135_reg_1415 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln51_134_reg_1400 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln51_133_reg_1385 == 1'd1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln51_132_reg_1370 == 1'd1)))) begin
        out2_blk_n = out2_full_n;
    end else begin
        out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln51_136_reg_1430 == 1'd1))) begin
        out2_din = 10'd9;
    end else if (((1'b0 == ap_block_state10) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln51_135_reg_1415 == 1'd1))) begin
        out2_din = 10'd8;
    end else if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln51_134_reg_1400 == 1'd1))) begin
        out2_din = 10'd7;
    end else if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln51_133_reg_1385 == 1'd1))) begin
        out2_din = 10'd6;
    end else if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln51_132_reg_1370 == 1'd1))) begin
        out2_din = 10'd5;
    end else if (((icmp_ln51_131_reg_1355 == 1'd1) & (1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        out2_din = 10'd4;
    end else if (((icmp_ln51_130_reg_1340 == 1'd1) & (1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        out2_din = 10'd3;
    end else if (((icmp_ln51_129_reg_1325 == 1'd1) & (1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        out2_din = 10'd2;
    end else if (((icmp_ln51_128_reg_1310 == 1'd1) & (1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        out2_din = 10'd1;
    end else if (((icmp_ln51_reg_1295 == 1'd1) & (1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        out2_din = 10'd0;
    end else begin
        out2_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln51_131_reg_1355 == 1'd1) & (1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)) | ((icmp_ln51_130_reg_1340 == 1'd1) & (1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln51_129_reg_1325 == 1'd1) & (1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln51_128_reg_1310 == 1'd1) & (1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln51_reg_1295 == 1'd1) & (1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)) | ((1'b0 == ap_block_state10) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln51_135_reg_1415 == 1'd1)) | ((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln51_134_reg_1400 == 1'd1)) | ((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln51_133_reg_1385 == 1'd1)) | ((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln51_132_reg_1370 == 1'd1)) | ((1'b0 == ap_block_state11) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln51_136_reg_1430 == 1'd1)))) begin
        out2_write = 1'b1;
    end else begin
        out2_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((1'b0 == ap_block_state11) & (tmp_s_nbreadreq_fu_161_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln56_128_fu_934_p2 = ($signed(sext_ln56_387_fu_928_p1) + $signed(zext_ln56_128_fu_931_p1));

assign add_ln56_129_fu_957_p2 = ($signed(sext_ln56_389_fu_951_p1) + $signed(zext_ln56_129_fu_954_p1));

assign add_ln56_130_fu_980_p2 = ($signed(sext_ln56_391_fu_974_p1) + $signed(zext_ln56_130_fu_977_p1));

assign add_ln56_131_fu_1003_p2 = ($signed(sext_ln56_393_fu_997_p1) + $signed(zext_ln56_131_fu_1000_p1));

assign add_ln56_132_fu_1026_p2 = ($signed(sext_ln56_395_fu_1020_p1) + $signed(zext_ln56_132_fu_1023_p1));

assign add_ln56_133_fu_1049_p2 = ($signed(sext_ln56_397_fu_1043_p1) + $signed(zext_ln56_133_fu_1046_p1));

assign add_ln56_134_fu_1072_p2 = ($signed(sext_ln56_399_fu_1066_p1) + $signed(zext_ln56_134_fu_1069_p1));

assign add_ln56_135_fu_1095_p2 = ($signed(sext_ln56_401_fu_1089_p1) + $signed(zext_ln56_135_fu_1092_p1));

assign add_ln56_136_fu_1118_p2 = ($signed(sext_ln56_403_fu_1112_p1) + $signed(zext_ln56_136_fu_1115_p1));

assign add_ln56_256_fu_341_p2 = ($signed(sext_ln56_384_fu_337_p1) + $signed(sext_ln56_fu_325_p1));

assign add_ln56_257_fu_401_p2 = ($signed(sext_ln56_386_fu_397_p1) + $signed(sext_ln56_257_fu_385_p1));

assign add_ln56_258_fu_461_p2 = ($signed(sext_ln56_388_fu_457_p1) + $signed(sext_ln56_259_fu_445_p1));

assign add_ln56_259_fu_521_p2 = ($signed(sext_ln56_390_fu_517_p1) + $signed(sext_ln56_261_fu_505_p1));

assign add_ln56_260_fu_581_p2 = ($signed(sext_ln56_392_fu_577_p1) + $signed(sext_ln56_263_fu_565_p1));

assign add_ln56_261_fu_641_p2 = ($signed(sext_ln56_394_fu_637_p1) + $signed(sext_ln56_265_fu_625_p1));

assign add_ln56_262_fu_701_p2 = ($signed(sext_ln56_396_fu_697_p1) + $signed(sext_ln56_267_fu_685_p1));

assign add_ln56_263_fu_761_p2 = ($signed(sext_ln56_398_fu_757_p1) + $signed(sext_ln56_269_fu_745_p1));

assign add_ln56_264_fu_821_p2 = ($signed(sext_ln56_400_fu_817_p1) + $signed(sext_ln56_271_fu_805_p1));

assign add_ln56_265_fu_881_p2 = ($signed(sext_ln56_402_fu_877_p1) + $signed(sext_ln56_273_fu_865_p1));

assign add_ln56_fu_911_p2 = ($signed(sext_ln56_385_fu_905_p1) + $signed(zext_ln56_fu_908_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((out2_full_n == 1'b0) & (icmp_ln51_135_reg_1415 == 1'd1));
end

always @ (*) begin
    ap_block_state11 = ((out2_full_n == 1'b0) & (icmp_ln51_136_reg_1430 == 1'd1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_reg_1295 == 1'd1) & (out2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln51_128_reg_1310 == 1'd1) & (out2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((icmp_ln51_129_reg_1325 == 1'd1) & (out2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((icmp_ln51_130_reg_1340 == 1'd1) & (out2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((icmp_ln51_131_reg_1355 == 1'd1) & (out2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((out2_full_n == 1'b0) & (icmp_ln51_132_reg_1370 == 1'd1));
end

always @ (*) begin
    ap_block_state8 = ((out2_full_n == 1'b0) & (icmp_ln51_133_reg_1385 == 1'd1));
end

always @ (*) begin
    ap_block_state9 = ((out2_full_n == 1'b0) & (icmp_ln51_134_reg_1400 == 1'd1));
end

assign grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start = grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg;

assign icmp_ln51_128_fu_379_p2 = (($signed(tmp_387_fu_369_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_129_fu_439_p2 = (($signed(tmp_390_fu_429_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_130_fu_499_p2 = (($signed(tmp_393_fu_489_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_131_fu_559_p2 = (($signed(tmp_396_fu_549_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_132_fu_619_p2 = (($signed(tmp_399_fu_609_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_133_fu_679_p2 = (($signed(tmp_402_fu_669_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_134_fu_739_p2 = (($signed(tmp_405_fu_729_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_135_fu_799_p2 = (($signed(tmp_408_fu_789_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_136_fu_859_p2 = (($signed(tmp_411_fu_849_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_319_p2 = (($signed(tmp_fu_309_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign p_promoted10_fu_986_p3 = ((icmp_ln51_130_reg_1340[0:0] == 1'b1) ? 9'd0 : add_ln56_130_fu_980_p2);

assign p_promoted12_fu_1009_p3 = ((icmp_ln51_131_reg_1355[0:0] == 1'b1) ? 9'd0 : add_ln56_131_fu_1003_p2);

assign p_promoted14_fu_1032_p3 = ((icmp_ln51_132_reg_1370[0:0] == 1'b1) ? 9'd0 : add_ln56_132_fu_1026_p2);

assign p_promoted16_fu_1055_p3 = ((icmp_ln51_133_reg_1385[0:0] == 1'b1) ? 9'd0 : add_ln56_133_fu_1049_p2);

assign p_promoted18_fu_1078_p3 = ((icmp_ln51_134_reg_1400[0:0] == 1'b1) ? 9'd0 : add_ln56_134_fu_1072_p2);

assign p_promoted20_fu_1101_p3 = ((icmp_ln51_135_reg_1415[0:0] == 1'b1) ? 9'd0 : add_ln56_135_fu_1095_p2);

assign p_promoted22_fu_1124_p3 = ((icmp_ln51_136_reg_1430[0:0] == 1'b1) ? 9'd0 : add_ln56_136_fu_1118_p2);

assign p_promoted6_fu_940_p3 = ((icmp_ln51_128_reg_1310[0:0] == 1'b1) ? 9'd0 : add_ln56_128_fu_934_p2);

assign p_promoted8_fu_963_p3 = ((icmp_ln51_129_reg_1325[0:0] == 1'b1) ? 9'd0 : add_ln56_129_fu_957_p2);

assign p_promoted_fu_917_p3 = ((icmp_ln51_reg_1295[0:0] == 1'b1) ? 9'd0 : add_ln56_fu_911_p2);

assign sext_ln51_127_fu_947_p1 = p_promoted6_fu_940_p3;

assign sext_ln51_128_fu_970_p1 = p_promoted8_fu_963_p3;

assign sext_ln51_129_fu_993_p1 = p_promoted10_fu_986_p3;

assign sext_ln51_130_fu_1016_p1 = p_promoted12_fu_1009_p3;

assign sext_ln51_131_fu_1039_p1 = p_promoted14_fu_1032_p3;

assign sext_ln51_132_fu_1062_p1 = p_promoted16_fu_1055_p3;

assign sext_ln51_133_fu_1085_p1 = p_promoted18_fu_1078_p3;

assign sext_ln51_134_fu_1108_p1 = p_promoted20_fu_1101_p3;

assign sext_ln51_fu_924_p1 = p_promoted_fu_917_p3;

assign sext_ln56_257_fu_385_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;

assign sext_ln56_257_fu_385_p1 = sext_ln56_257_fu_385_p0;

assign sext_ln56_259_fu_445_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;

assign sext_ln56_259_fu_445_p1 = sext_ln56_259_fu_445_p0;

assign sext_ln56_261_fu_505_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;

assign sext_ln56_261_fu_505_p1 = sext_ln56_261_fu_505_p0;

assign sext_ln56_263_fu_565_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;

assign sext_ln56_263_fu_565_p1 = sext_ln56_263_fu_565_p0;

assign sext_ln56_265_fu_625_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;

assign sext_ln56_265_fu_625_p1 = sext_ln56_265_fu_625_p0;

assign sext_ln56_267_fu_685_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;

assign sext_ln56_267_fu_685_p1 = sext_ln56_267_fu_685_p0;

assign sext_ln56_269_fu_745_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;

assign sext_ln56_269_fu_745_p1 = sext_ln56_269_fu_745_p0;

assign sext_ln56_271_fu_805_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;

assign sext_ln56_271_fu_805_p1 = sext_ln56_271_fu_805_p0;

assign sext_ln56_273_fu_865_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;

assign sext_ln56_273_fu_865_p1 = sext_ln56_273_fu_865_p0;

assign sext_ln56_384_fu_337_p1 = $signed(tmp_385_fu_329_p3);

assign sext_ln56_385_fu_905_p1 = $signed(trunc_ln_reg_1300);

assign sext_ln56_386_fu_397_p1 = $signed(tmp_388_fu_389_p3);

assign sext_ln56_387_fu_928_p1 = $signed(trunc_ln56_s_reg_1315);

assign sext_ln56_388_fu_457_p1 = $signed(tmp_391_fu_449_p3);

assign sext_ln56_389_fu_951_p1 = $signed(trunc_ln56_127_reg_1330);

assign sext_ln56_390_fu_517_p1 = $signed(tmp_394_fu_509_p3);

assign sext_ln56_391_fu_974_p1 = $signed(trunc_ln56_128_reg_1345);

assign sext_ln56_392_fu_577_p1 = $signed(tmp_397_fu_569_p3);

assign sext_ln56_393_fu_997_p1 = $signed(trunc_ln56_129_reg_1360);

assign sext_ln56_394_fu_637_p1 = $signed(tmp_400_fu_629_p3);

assign sext_ln56_395_fu_1020_p1 = $signed(trunc_ln56_130_reg_1375);

assign sext_ln56_396_fu_697_p1 = $signed(tmp_403_fu_689_p3);

assign sext_ln56_397_fu_1043_p1 = $signed(trunc_ln56_131_reg_1390);

assign sext_ln56_398_fu_757_p1 = $signed(tmp_406_fu_749_p3);

assign sext_ln56_399_fu_1066_p1 = $signed(trunc_ln56_132_reg_1405);

assign sext_ln56_400_fu_817_p1 = $signed(tmp_409_fu_809_p3);

assign sext_ln56_401_fu_1089_p1 = $signed(trunc_ln56_133_reg_1420);

assign sext_ln56_402_fu_877_p1 = $signed(tmp_412_fu_869_p3);

assign sext_ln56_403_fu_1112_p1 = $signed(trunc_ln56_134_reg_1435);

assign sext_ln56_fu_325_p0 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;

assign sext_ln56_fu_325_p1 = sext_ln56_fu_325_p0;

assign sext_ln63_fu_1131_p1 = p_promoted22_fu_1124_p3;

assign tmp_385_fu_329_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;

assign tmp_385_fu_329_p3 = {{tmp_385_fu_329_p1}, {6'd0}};

assign tmp_387_fu_369_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;

assign tmp_387_fu_369_p4 = {{tmp_387_fu_369_p1[15:10]}};

assign tmp_388_fu_389_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;

assign tmp_388_fu_389_p3 = {{tmp_388_fu_389_p1}, {6'd0}};

assign tmp_390_fu_429_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;

assign tmp_390_fu_429_p4 = {{tmp_390_fu_429_p1[15:10]}};

assign tmp_391_fu_449_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;

assign tmp_391_fu_449_p3 = {{tmp_391_fu_449_p1}, {6'd0}};

assign tmp_393_fu_489_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;

assign tmp_393_fu_489_p4 = {{tmp_393_fu_489_p1[15:10]}};

assign tmp_394_fu_509_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;

assign tmp_394_fu_509_p3 = {{tmp_394_fu_509_p1}, {6'd0}};

assign tmp_396_fu_549_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;

assign tmp_396_fu_549_p4 = {{tmp_396_fu_549_p1[15:10]}};

assign tmp_397_fu_569_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;

assign tmp_397_fu_569_p3 = {{tmp_397_fu_569_p1}, {6'd0}};

assign tmp_399_fu_609_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;

assign tmp_399_fu_609_p4 = {{tmp_399_fu_609_p1[15:10]}};

assign tmp_400_fu_629_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;

assign tmp_400_fu_629_p3 = {{tmp_400_fu_629_p1}, {6'd0}};

assign tmp_402_fu_669_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;

assign tmp_402_fu_669_p4 = {{tmp_402_fu_669_p1[15:10]}};

assign tmp_403_fu_689_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;

assign tmp_403_fu_689_p3 = {{tmp_403_fu_689_p1}, {6'd0}};

assign tmp_405_fu_729_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;

assign tmp_405_fu_729_p4 = {{tmp_405_fu_729_p1[15:10]}};

assign tmp_406_fu_749_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;

assign tmp_406_fu_749_p3 = {{tmp_406_fu_749_p1}, {6'd0}};

assign tmp_408_fu_789_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;

assign tmp_408_fu_789_p4 = {{tmp_408_fu_789_p1[15:10]}};

assign tmp_409_fu_809_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;

assign tmp_409_fu_809_p3 = {{tmp_409_fu_809_p1}, {6'd0}};

assign tmp_411_fu_849_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;

assign tmp_411_fu_849_p4 = {{tmp_411_fu_849_p1[15:10]}};

assign tmp_412_fu_869_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;

assign tmp_412_fu_869_p3 = {{tmp_412_fu_869_p1}, {6'd0}};

assign tmp_fu_309_p1 = void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;

assign tmp_fu_309_p4 = {{tmp_fu_309_p1[15:10]}};

assign tmp_s_nbreadreq_fu_161_p3 = out1_empty_n;

assign zext_ln56_128_fu_931_p1 = tmp_389_reg_1320;

assign zext_ln56_129_fu_954_p1 = tmp_392_reg_1335;

assign zext_ln56_130_fu_977_p1 = tmp_395_reg_1350;

assign zext_ln56_131_fu_1000_p1 = tmp_398_reg_1365;

assign zext_ln56_132_fu_1023_p1 = tmp_401_reg_1380;

assign zext_ln56_133_fu_1046_p1 = tmp_404_reg_1395;

assign zext_ln56_134_fu_1069_p1 = tmp_407_reg_1410;

assign zext_ln56_135_fu_1092_p1 = tmp_410_reg_1425;

assign zext_ln56_136_fu_1115_p1 = tmp_413_reg_1440;

assign zext_ln56_fu_908_p1 = tmp_386_reg_1305;

endmodule //snn_mnist_hls_lif_layer_10_128_stream_ap_uint_10_0_stream_ap_uint_10_0_1_s
