-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_mnist_hls_lif_layer_10_128_stream_ap_uint_10_0_stream_ap_uint_10_0_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out1_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    out1_empty_n : IN STD_LOGIC;
    out1_read : OUT STD_LOGIC;
    out2_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    out2_full_n : IN STD_LOGIC;
    out2_write : OUT STD_LOGIC );
end;


architecture behav of snn_mnist_hls_lif_layer_10_128_stream_ap_uint_10_0_stream_ap_uint_10_0_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv10_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_const_lv10_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000000101";
    constant ap_const_lv10_6 : STD_LOGIC_VECTOR (9 downto 0) := "0000000110";
    constant ap_const_lv10_7 : STD_LOGIC_VECTOR (9 downto 0) := "0000000111";
    constant ap_const_lv10_8 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_const_lv10_9 : STD_LOGIC_VECTOR (9 downto 0) := "0000001001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal out2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln51_reg_1295 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln51_128_reg_1310 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln51_129_reg_1325 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln51_130_reg_1340 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln51_131_reg_1355 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln51_132_reg_1370 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln51_133_reg_1385 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln51_134_reg_1400 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln51_135_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal icmp_ln51_136_reg_1430 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_1300 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_386_reg_1305 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_128_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_s_reg_1315 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_389_reg_1320 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_129_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_127_reg_1330 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_392_reg_1335 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_130_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_128_reg_1345 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_395_reg_1350 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_131_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_129_reg_1360 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_398_reg_1365 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_132_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_130_reg_1375 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_401_reg_1380 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_133_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_131_reg_1390 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_404_reg_1395 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_134_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_132_reg_1405 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_407_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_135_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_133_reg_1420 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_410_reg_1425 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_136_fu_859_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_134_reg_1435 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_413_reg_1440 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_promoted_fu_917_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted_reg_1445 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_fu_924_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_reg_1450 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted6_fu_940_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted6_reg_1455 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_127_fu_947_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_127_reg_1460 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted8_fu_963_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted8_reg_1465 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_128_fu_970_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_128_reg_1470 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted10_fu_986_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted10_reg_1475 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_129_fu_993_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_129_reg_1480 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted12_fu_1009_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted12_reg_1485 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_130_fu_1016_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_130_reg_1490 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted14_fu_1032_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted14_reg_1495 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_131_fu_1039_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_131_reg_1500 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted16_fu_1055_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted16_reg_1505 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_132_fu_1062_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_132_reg_1510 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted18_fu_1078_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted18_reg_1515 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_133_fu_1085_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_133_reg_1520 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted20_fu_1101_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted20_reg_1525 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln51_134_fu_1108_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln51_134_reg_1530 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_promoted22_fu_1124_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_promoted22_reg_1535 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln63_fu_1131_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln63_reg_1540 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_nbreadreq_fu_161_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1545 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_idle : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld : STD_LOGIC;
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld : STD_LOGIC;
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state11 : BOOLEAN;
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal add_ln74_loc_fu_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_128_loc_fu_136 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_129_loc_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_130_loc_fu_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_131_loc_fu_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_132_loc_fu_120 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_133_loc_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_134_loc_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_135_loc_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln74_136_loc_fu_104 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state7 : BOOLEAN;
    signal ap_block_state8 : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal ap_block_state10 : BOOLEAN;
    signal tmp_fu_309_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_309_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_fu_325_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_385_fu_329_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_385_fu_329_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_384_fu_337_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_fu_325_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_256_fu_341_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_387_fu_369_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_387_fu_369_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_257_fu_385_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_388_fu_389_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_388_fu_389_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_386_fu_397_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_257_fu_385_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_257_fu_401_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_390_fu_429_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_390_fu_429_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_259_fu_445_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_391_fu_449_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_391_fu_449_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_388_fu_457_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_259_fu_445_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_258_fu_461_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_393_fu_489_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_393_fu_489_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_261_fu_505_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_394_fu_509_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_394_fu_509_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_390_fu_517_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_261_fu_505_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_259_fu_521_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_396_fu_549_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_396_fu_549_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_263_fu_565_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_397_fu_569_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_397_fu_569_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_392_fu_577_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_263_fu_565_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_260_fu_581_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_399_fu_609_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_399_fu_609_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_265_fu_625_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_400_fu_629_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_400_fu_629_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_394_fu_637_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_265_fu_625_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_261_fu_641_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_402_fu_669_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_402_fu_669_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_267_fu_685_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_403_fu_689_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_403_fu_689_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_396_fu_697_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_267_fu_685_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_262_fu_701_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_405_fu_729_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_405_fu_729_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_269_fu_745_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_406_fu_749_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_406_fu_749_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_398_fu_757_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_269_fu_745_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_263_fu_761_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_408_fu_789_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_408_fu_789_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_271_fu_805_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_409_fu_809_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_409_fu_809_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_400_fu_817_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_271_fu_805_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_264_fu_821_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_411_fu_849_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_411_fu_849_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln56_273_fu_865_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_412_fu_869_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_412_fu_869_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln56_402_fu_877_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_273_fu_865_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln56_265_fu_881_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_385_fu_905_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_fu_908_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_fu_911_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_387_fu_928_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_128_fu_931_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_128_fu_934_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_389_fu_951_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_129_fu_954_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_129_fu_957_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_391_fu_974_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_130_fu_977_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_130_fu_980_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_393_fu_997_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_131_fu_1000_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_131_fu_1003_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_395_fu_1020_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_132_fu_1023_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_132_fu_1026_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_397_fu_1043_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_133_fu_1046_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_133_fu_1049_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_399_fu_1066_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_134_fu_1069_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_134_fu_1072_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_401_fu_1089_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_135_fu_1092_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_135_fu_1095_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_403_fu_1112_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_136_fu_1115_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_136_fu_1118_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_mnist_hls_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_promoted22 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted20 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted18 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted16 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted14 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted12 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted10 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted8 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted6 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_promoted : IN STD_LOGIC_VECTOR (8 downto 0);
        out1_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        out1_empty_n : IN STD_LOGIC;
        out1_read : OUT STD_LOGIC;
        add_ln74_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_out_ap_vld : OUT STD_LOGIC;
        add_ln74_128_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_128_out_ap_vld : OUT STD_LOGIC;
        add_ln74_129_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_129_out_ap_vld : OUT STD_LOGIC;
        add_ln74_130_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_130_out_ap_vld : OUT STD_LOGIC;
        add_ln74_131_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_131_out_ap_vld : OUT STD_LOGIC;
        add_ln74_132_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_132_out_ap_vld : OUT STD_LOGIC;
        add_ln74_133_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_133_out_ap_vld : OUT STD_LOGIC;
        add_ln74_134_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_134_out_ap_vld : OUT STD_LOGIC;
        add_ln74_135_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_135_out_ap_vld : OUT STD_LOGIC;
        add_ln74_136_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        add_ln74_136_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259 : component snn_mnist_hls_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start,
        ap_done => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done,
        ap_idle => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_idle,
        ap_ready => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready,
        p_promoted22 => p_promoted22_reg_1535,
        p_promoted20 => p_promoted20_reg_1525,
        p_promoted18 => p_promoted18_reg_1515,
        p_promoted16 => p_promoted16_reg_1505,
        p_promoted14 => p_promoted14_reg_1495,
        p_promoted12 => p_promoted12_reg_1485,
        p_promoted10 => p_promoted10_reg_1475,
        p_promoted8 => p_promoted8_reg_1465,
        p_promoted6 => p_promoted6_reg_1455,
        p_promoted => p_promoted_reg_1445,
        out1_dout => out1_dout,
        out1_empty_n => out1_empty_n,
        out1_read => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read,
        add_ln74_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out,
        add_ln74_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld,
        add_ln74_128_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out,
        add_ln74_128_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld,
        add_ln74_129_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out,
        add_ln74_129_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld,
        add_ln74_130_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out,
        add_ln74_130_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld,
        add_ln74_131_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out,
        add_ln74_131_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld,
        add_ln74_132_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out,
        add_ln74_132_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld,
        add_ln74_133_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out,
        add_ln74_133_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld,
        add_ln74_134_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out,
        add_ln74_134_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld,
        add_ln74_135_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out,
        add_ln74_135_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld,
        add_ln74_136_out => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out,
        add_ln74_136_out_ap_vld => grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_ready = ap_const_logic_1)) then 
                    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178 <= add_ln74_128_loc_fu_136;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178 <= sext_ln51_127_reg_1460;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196 <= add_ln74_129_loc_fu_132;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196 <= sext_ln51_128_reg_1470;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205 <= add_ln74_130_loc_fu_128;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205 <= sext_ln51_129_reg_1480;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214 <= add_ln74_131_loc_fu_124;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214 <= sext_ln51_130_reg_1490;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223 <= add_ln74_132_loc_fu_120;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223 <= sext_ln51_131_reg_1500;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232 <= add_ln74_133_loc_fu_116;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232 <= sext_ln51_132_reg_1510;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241 <= add_ln74_134_loc_fu_112;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241 <= sext_ln51_133_reg_1520;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250 <= add_ln74_135_loc_fu_108;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250 <= sext_ln51_134_reg_1530;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187 <= add_ln74_136_loc_fu_104;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187 <= sext_ln63_reg_1540;
            end if; 
        end if;
    end process;

    void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169 <= add_ln74_loc_fu_140;
            elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169 <= sext_ln51_reg_1450;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_128_loc_fu_136 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_128_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_129_loc_fu_132 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_129_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_130_loc_fu_128 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_130_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_131_loc_fu_124 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_131_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_132_loc_fu_120 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_132_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_133_loc_fu_116 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_133_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_134_loc_fu_112 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_134_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_135_loc_fu_108 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_135_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_136_loc_fu_104 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_136_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                add_ln74_loc_fu_140 <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_add_ln74_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln51_128_reg_1310 <= icmp_ln51_128_fu_379_p2;
                icmp_ln51_129_reg_1325 <= icmp_ln51_129_fu_439_p2;
                icmp_ln51_130_reg_1340 <= icmp_ln51_130_fu_499_p2;
                icmp_ln51_131_reg_1355 <= icmp_ln51_131_fu_559_p2;
                icmp_ln51_132_reg_1370 <= icmp_ln51_132_fu_619_p2;
                icmp_ln51_133_reg_1385 <= icmp_ln51_133_fu_679_p2;
                icmp_ln51_134_reg_1400 <= icmp_ln51_134_fu_739_p2;
                icmp_ln51_135_reg_1415 <= icmp_ln51_135_fu_799_p2;
                icmp_ln51_136_reg_1430 <= icmp_ln51_136_fu_859_p2;
                icmp_ln51_reg_1295 <= icmp_ln51_fu_319_p2;
                tmp_386_reg_1305 <= add_ln56_256_fu_341_p2(15 downto 15);
                tmp_389_reg_1320 <= add_ln56_257_fu_401_p2(15 downto 15);
                tmp_392_reg_1335 <= add_ln56_258_fu_461_p2(15 downto 15);
                tmp_395_reg_1350 <= add_ln56_259_fu_521_p2(15 downto 15);
                tmp_398_reg_1365 <= add_ln56_260_fu_581_p2(15 downto 15);
                tmp_401_reg_1380 <= add_ln56_261_fu_641_p2(15 downto 15);
                tmp_404_reg_1395 <= add_ln56_262_fu_701_p2(15 downto 15);
                tmp_407_reg_1410 <= add_ln56_263_fu_761_p2(15 downto 15);
                tmp_410_reg_1425 <= add_ln56_264_fu_821_p2(15 downto 15);
                tmp_413_reg_1440 <= add_ln56_265_fu_881_p2(15 downto 15);
                trunc_ln56_127_reg_1330 <= add_ln56_258_fu_461_p2(23 downto 16);
                trunc_ln56_128_reg_1345 <= add_ln56_259_fu_521_p2(23 downto 16);
                trunc_ln56_129_reg_1360 <= add_ln56_260_fu_581_p2(23 downto 16);
                trunc_ln56_130_reg_1375 <= add_ln56_261_fu_641_p2(23 downto 16);
                trunc_ln56_131_reg_1390 <= add_ln56_262_fu_701_p2(23 downto 16);
                trunc_ln56_132_reg_1405 <= add_ln56_263_fu_761_p2(23 downto 16);
                trunc_ln56_133_reg_1420 <= add_ln56_264_fu_821_p2(23 downto 16);
                trunc_ln56_134_reg_1435 <= add_ln56_265_fu_881_p2(23 downto 16);
                trunc_ln56_s_reg_1315 <= add_ln56_257_fu_401_p2(23 downto 16);
                trunc_ln_reg_1300 <= add_ln56_256_fu_341_p2(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_promoted10_reg_1475 <= p_promoted10_fu_986_p3;
                p_promoted12_reg_1485 <= p_promoted12_fu_1009_p3;
                p_promoted14_reg_1495 <= p_promoted14_fu_1032_p3;
                p_promoted16_reg_1505 <= p_promoted16_fu_1055_p3;
                p_promoted18_reg_1515 <= p_promoted18_fu_1078_p3;
                p_promoted20_reg_1525 <= p_promoted20_fu_1101_p3;
                p_promoted22_reg_1535 <= p_promoted22_fu_1124_p3;
                p_promoted6_reg_1455 <= p_promoted6_fu_940_p3;
                p_promoted8_reg_1465 <= p_promoted8_fu_963_p3;
                p_promoted_reg_1445 <= p_promoted_fu_917_p3;
                sext_ln51_127_reg_1460 <= sext_ln51_127_fu_947_p1;
                sext_ln51_128_reg_1470 <= sext_ln51_128_fu_970_p1;
                sext_ln51_129_reg_1480 <= sext_ln51_129_fu_993_p1;
                sext_ln51_130_reg_1490 <= sext_ln51_130_fu_1016_p1;
                sext_ln51_131_reg_1500 <= sext_ln51_131_fu_1039_p1;
                sext_ln51_132_reg_1510 <= sext_ln51_132_fu_1062_p1;
                sext_ln51_133_reg_1520 <= sext_ln51_133_fu_1085_p1;
                sext_ln51_134_reg_1530 <= sext_ln51_134_fu_1108_p1;
                sext_ln51_reg_1450 <= sext_ln51_fu_924_p1;
                sext_ln63_reg_1540 <= sext_ln63_fu_1131_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                tmp_s_reg_1545 <= tmp_s_nbreadreq_fu_161_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4;
                void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9 <= ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, tmp_s_nbreadreq_fu_161_p3, grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done, ap_block_state11, ap_CS_fsm_state13, ap_block_state2, ap_block_state3, ap_block_state4, ap_block_state5, ap_block_state6, ap_block_state7, ap_block_state8, ap_block_state9, ap_block_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_boolean_0 = ap_block_state7) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((ap_const_boolean_0 = ap_block_state10) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((ap_const_boolean_0 = ap_block_state11) and (tmp_s_nbreadreq_fu_161_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln56_128_fu_934_p2 <= std_logic_vector(signed(sext_ln56_387_fu_928_p1) + signed(zext_ln56_128_fu_931_p1));
    add_ln56_129_fu_957_p2 <= std_logic_vector(signed(sext_ln56_389_fu_951_p1) + signed(zext_ln56_129_fu_954_p1));
    add_ln56_130_fu_980_p2 <= std_logic_vector(signed(sext_ln56_391_fu_974_p1) + signed(zext_ln56_130_fu_977_p1));
    add_ln56_131_fu_1003_p2 <= std_logic_vector(signed(sext_ln56_393_fu_997_p1) + signed(zext_ln56_131_fu_1000_p1));
    add_ln56_132_fu_1026_p2 <= std_logic_vector(signed(sext_ln56_395_fu_1020_p1) + signed(zext_ln56_132_fu_1023_p1));
    add_ln56_133_fu_1049_p2 <= std_logic_vector(signed(sext_ln56_397_fu_1043_p1) + signed(zext_ln56_133_fu_1046_p1));
    add_ln56_134_fu_1072_p2 <= std_logic_vector(signed(sext_ln56_399_fu_1066_p1) + signed(zext_ln56_134_fu_1069_p1));
    add_ln56_135_fu_1095_p2 <= std_logic_vector(signed(sext_ln56_401_fu_1089_p1) + signed(zext_ln56_135_fu_1092_p1));
    add_ln56_136_fu_1118_p2 <= std_logic_vector(signed(sext_ln56_403_fu_1112_p1) + signed(zext_ln56_136_fu_1115_p1));
    add_ln56_256_fu_341_p2 <= std_logic_vector(signed(sext_ln56_384_fu_337_p1) + signed(sext_ln56_fu_325_p1));
    add_ln56_257_fu_401_p2 <= std_logic_vector(signed(sext_ln56_386_fu_397_p1) + signed(sext_ln56_257_fu_385_p1));
    add_ln56_258_fu_461_p2 <= std_logic_vector(signed(sext_ln56_388_fu_457_p1) + signed(sext_ln56_259_fu_445_p1));
    add_ln56_259_fu_521_p2 <= std_logic_vector(signed(sext_ln56_390_fu_517_p1) + signed(sext_ln56_261_fu_505_p1));
    add_ln56_260_fu_581_p2 <= std_logic_vector(signed(sext_ln56_392_fu_577_p1) + signed(sext_ln56_263_fu_565_p1));
    add_ln56_261_fu_641_p2 <= std_logic_vector(signed(sext_ln56_394_fu_637_p1) + signed(sext_ln56_265_fu_625_p1));
    add_ln56_262_fu_701_p2 <= std_logic_vector(signed(sext_ln56_396_fu_697_p1) + signed(sext_ln56_267_fu_685_p1));
    add_ln56_263_fu_761_p2 <= std_logic_vector(signed(sext_ln56_398_fu_757_p1) + signed(sext_ln56_269_fu_745_p1));
    add_ln56_264_fu_821_p2 <= std_logic_vector(signed(sext_ln56_400_fu_817_p1) + signed(sext_ln56_271_fu_805_p1));
    add_ln56_265_fu_881_p2 <= std_logic_vector(signed(sext_ln56_402_fu_877_p1) + signed(sext_ln56_273_fu_865_p1));
    add_ln56_fu_911_p2 <= std_logic_vector(signed(sext_ln56_385_fu_905_p1) + signed(zext_ln56_fu_908_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(ap_block_state10)
    begin
        if ((ap_const_boolean_1 = ap_block_state10)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(ap_block_state11)
    begin
        if ((ap_const_boolean_1 = ap_block_state11)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done)
    begin
        if ((grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6)
    begin
        if ((ap_const_boolean_1 = ap_block_state6)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(ap_block_state7)
    begin
        if ((ap_const_boolean_1 = ap_block_state7)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8)
    begin
        if ((ap_const_boolean_1 = ap_block_state8)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9)
    begin
        if ((ap_const_boolean_1 = ap_block_state9)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state10_assign_proc : process(out2_full_n, icmp_ln51_135_reg_1415)
    begin
                ap_block_state10 <= ((out2_full_n = ap_const_logic_0) and (icmp_ln51_135_reg_1415 = ap_const_lv1_1));
    end process;


    ap_block_state11_assign_proc : process(out2_full_n, icmp_ln51_136_reg_1430)
    begin
                ap_block_state11 <= ((out2_full_n = ap_const_logic_0) and (icmp_ln51_136_reg_1430 = ap_const_lv1_1));
    end process;


    ap_block_state2_assign_proc : process(out2_full_n, icmp_ln51_reg_1295)
    begin
                ap_block_state2 <= ((icmp_ln51_reg_1295 = ap_const_lv1_1) and (out2_full_n = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(out2_full_n, icmp_ln51_128_reg_1310)
    begin
                ap_block_state3 <= ((icmp_ln51_128_reg_1310 = ap_const_lv1_1) and (out2_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(out2_full_n, icmp_ln51_129_reg_1325)
    begin
                ap_block_state4 <= ((icmp_ln51_129_reg_1325 = ap_const_lv1_1) and (out2_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(out2_full_n, icmp_ln51_130_reg_1340)
    begin
                ap_block_state5 <= ((icmp_ln51_130_reg_1340 = ap_const_lv1_1) and (out2_full_n = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(out2_full_n, icmp_ln51_131_reg_1355)
    begin
                ap_block_state6 <= ((icmp_ln51_131_reg_1355 = ap_const_lv1_1) and (out2_full_n = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(out2_full_n, icmp_ln51_132_reg_1370)
    begin
                ap_block_state7 <= ((out2_full_n = ap_const_logic_0) and (icmp_ln51_132_reg_1370 = ap_const_lv1_1));
    end process;


    ap_block_state8_assign_proc : process(out2_full_n, icmp_ln51_133_reg_1385)
    begin
                ap_block_state8 <= ((out2_full_n = ap_const_logic_0) and (icmp_ln51_133_reg_1385 = ap_const_lv1_1));
    end process;


    ap_block_state9_assign_proc : process(out2_full_n, icmp_ln51_134_reg_1400)
    begin
                ap_block_state9 <= ((out2_full_n = ap_const_logic_0) and (icmp_ln51_134_reg_1400 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178, add_ln74_128_loc_fu_136)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4 <= add_ln74_128_loc_fu_136;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_phi_fu_181_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_1_new_0_reg_178;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196, add_ln74_129_loc_fu_132)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4 <= add_ln74_129_loc_fu_132;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_phi_fu_199_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_2_new_0_reg_196;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205, add_ln74_130_loc_fu_128)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4 <= add_ln74_130_loc_fu_128;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_phi_fu_208_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_3_new_0_reg_205;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214, add_ln74_131_loc_fu_124)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4 <= add_ln74_131_loc_fu_124;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_phi_fu_217_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_4_new_0_reg_214;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223, add_ln74_132_loc_fu_120)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4 <= add_ln74_132_loc_fu_120;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_phi_fu_226_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_5_new_0_reg_223;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232, add_ln74_133_loc_fu_116)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4 <= add_ln74_133_loc_fu_116;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_phi_fu_235_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_6_new_0_reg_232;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241, add_ln74_134_loc_fu_112)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4 <= add_ln74_134_loc_fu_112;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_phi_fu_244_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_7_new_0_reg_241;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250, add_ln74_135_loc_fu_108)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4 <= add_ln74_135_loc_fu_108;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_phi_fu_253_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_8_new_0_reg_250;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4_assign_proc : process(tmp_s_reg_1545, ap_CS_fsm_state14, void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187, add_ln74_136_loc_fu_104)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4 <= add_ln74_136_loc_fu_104;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_phi_fu_190_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_9_new_0_reg_187;
        end if; 
    end process;


    ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4_assign_proc : process(tmp_s_reg_1545, void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169, ap_CS_fsm_state14, add_ln74_loc_fu_140)
    begin
        if (((tmp_s_reg_1545 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4 <= add_ln74_loc_fu_140;
        else 
            ap_phi_mux_void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_phi_fu_172_p4 <= void_lif_layer_stream_stream_ap_fixed_128_potentials_new_0_reg_169;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_ap_start_reg;
    icmp_ln51_128_fu_379_p2 <= "1" when (signed(tmp_387_fu_369_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_129_fu_439_p2 <= "1" when (signed(tmp_390_fu_429_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_130_fu_499_p2 <= "1" when (signed(tmp_393_fu_489_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_131_fu_559_p2 <= "1" when (signed(tmp_396_fu_549_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_132_fu_619_p2 <= "1" when (signed(tmp_399_fu_609_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_133_fu_679_p2 <= "1" when (signed(tmp_402_fu_669_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_134_fu_739_p2 <= "1" when (signed(tmp_405_fu_729_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_135_fu_799_p2 <= "1" when (signed(tmp_408_fu_789_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_136_fu_859_p2 <= "1" when (signed(tmp_411_fu_849_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln51_fu_319_p2 <= "1" when (signed(tmp_fu_309_p4) > signed(ap_const_lv6_0)) else "0";

    out1_read_assign_proc : process(grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out1_read <= grp_lif_layer_10_128_stream_stream_ap_uint_10_0_1_Pipeline_integrate_fu_259_out1_read;
        else 
            out1_read <= ap_const_logic_0;
        end if; 
    end process;


    out2_blk_n_assign_proc : process(out2_full_n, ap_CS_fsm_state2, icmp_ln51_reg_1295, ap_CS_fsm_state3, icmp_ln51_128_reg_1310, ap_CS_fsm_state4, icmp_ln51_129_reg_1325, ap_CS_fsm_state5, icmp_ln51_130_reg_1340, ap_CS_fsm_state6, icmp_ln51_131_reg_1355, ap_CS_fsm_state7, icmp_ln51_132_reg_1370, ap_CS_fsm_state8, icmp_ln51_133_reg_1385, ap_CS_fsm_state9, icmp_ln51_134_reg_1400, ap_CS_fsm_state10, icmp_ln51_135_reg_1415, ap_CS_fsm_state11, icmp_ln51_136_reg_1430)
    begin
        if ((((icmp_ln51_131_reg_1355 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((icmp_ln51_130_reg_1340 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln51_129_reg_1325 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln51_128_reg_1310 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln51_reg_1295 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln51_136_reg_1430 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln51_135_reg_1415 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln51_134_reg_1400 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln51_133_reg_1385 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln51_132_reg_1370 = ap_const_lv1_1)))) then 
            out2_blk_n <= out2_full_n;
        else 
            out2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out2_din_assign_proc : process(ap_CS_fsm_state2, icmp_ln51_reg_1295, ap_CS_fsm_state3, icmp_ln51_128_reg_1310, ap_CS_fsm_state4, icmp_ln51_129_reg_1325, ap_CS_fsm_state5, icmp_ln51_130_reg_1340, ap_CS_fsm_state6, icmp_ln51_131_reg_1355, ap_CS_fsm_state7, icmp_ln51_132_reg_1370, ap_CS_fsm_state8, icmp_ln51_133_reg_1385, ap_CS_fsm_state9, icmp_ln51_134_reg_1400, ap_CS_fsm_state10, icmp_ln51_135_reg_1415, ap_CS_fsm_state11, icmp_ln51_136_reg_1430, ap_block_state11, ap_block_state2, ap_block_state3, ap_block_state4, ap_block_state5, ap_block_state6, ap_block_state7, ap_block_state8, ap_block_state9, ap_block_state10)
    begin
        if (((ap_const_boolean_0 = ap_block_state11) and (ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln51_136_reg_1430 = ap_const_lv1_1))) then 
            out2_din <= ap_const_lv10_9;
        elsif (((ap_const_boolean_0 = ap_block_state10) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln51_135_reg_1415 = ap_const_lv1_1))) then 
            out2_din <= ap_const_lv10_8;
        elsif (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln51_134_reg_1400 = ap_const_lv1_1))) then 
            out2_din <= ap_const_lv10_7;
        elsif (((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln51_133_reg_1385 = ap_const_lv1_1))) then 
            out2_din <= ap_const_lv10_6;
        elsif (((ap_const_boolean_0 = ap_block_state7) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln51_132_reg_1370 = ap_const_lv1_1))) then 
            out2_din <= ap_const_lv10_5;
        elsif (((icmp_ln51_131_reg_1355 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            out2_din <= ap_const_lv10_4;
        elsif (((icmp_ln51_130_reg_1340 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out2_din <= ap_const_lv10_3;
        elsif (((icmp_ln51_129_reg_1325 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out2_din <= ap_const_lv10_2;
        elsif (((icmp_ln51_128_reg_1310 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            out2_din <= ap_const_lv10_1;
        elsif (((icmp_ln51_reg_1295 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out2_din <= ap_const_lv10_0;
        else 
            out2_din <= "XXXXXXXXXX";
        end if; 
    end process;


    out2_write_assign_proc : process(ap_CS_fsm_state2, icmp_ln51_reg_1295, ap_CS_fsm_state3, icmp_ln51_128_reg_1310, ap_CS_fsm_state4, icmp_ln51_129_reg_1325, ap_CS_fsm_state5, icmp_ln51_130_reg_1340, ap_CS_fsm_state6, icmp_ln51_131_reg_1355, ap_CS_fsm_state7, icmp_ln51_132_reg_1370, ap_CS_fsm_state8, icmp_ln51_133_reg_1385, ap_CS_fsm_state9, icmp_ln51_134_reg_1400, ap_CS_fsm_state10, icmp_ln51_135_reg_1415, ap_CS_fsm_state11, icmp_ln51_136_reg_1430, ap_block_state11, ap_block_state2, ap_block_state3, ap_block_state4, ap_block_state5, ap_block_state6, ap_block_state7, ap_block_state8, ap_block_state9, ap_block_state10)
    begin
        if ((((icmp_ln51_131_reg_1355 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((icmp_ln51_130_reg_1340 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln51_129_reg_1325 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln51_128_reg_1310 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln51_reg_1295 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_boolean_0 = ap_block_state10) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln51_135_reg_1415 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln51_134_reg_1400 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln51_133_reg_1385 
    = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state7) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln51_132_reg_1370 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state11) and (ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln51_136_reg_1430 = ap_const_lv1_1)))) then 
            out2_write <= ap_const_logic_1;
        else 
            out2_write <= ap_const_logic_0;
        end if; 
    end process;

    p_promoted10_fu_986_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_130_reg_1340(0) = '1') else 
        add_ln56_130_fu_980_p2;
    p_promoted12_fu_1009_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_131_reg_1355(0) = '1') else 
        add_ln56_131_fu_1003_p2;
    p_promoted14_fu_1032_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_132_reg_1370(0) = '1') else 
        add_ln56_132_fu_1026_p2;
    p_promoted16_fu_1055_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_133_reg_1385(0) = '1') else 
        add_ln56_133_fu_1049_p2;
    p_promoted18_fu_1078_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_134_reg_1400(0) = '1') else 
        add_ln56_134_fu_1072_p2;
    p_promoted20_fu_1101_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_135_reg_1415(0) = '1') else 
        add_ln56_135_fu_1095_p2;
    p_promoted22_fu_1124_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_136_reg_1430(0) = '1') else 
        add_ln56_136_fu_1118_p2;
    p_promoted6_fu_940_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_128_reg_1310(0) = '1') else 
        add_ln56_128_fu_934_p2;
    p_promoted8_fu_963_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_129_reg_1325(0) = '1') else 
        add_ln56_129_fu_957_p2;
    p_promoted_fu_917_p3 <= 
        ap_const_lv9_0 when (icmp_ln51_reg_1295(0) = '1') else 
        add_ln56_fu_911_p2;
        sext_ln51_127_fu_947_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted6_fu_940_p3),16));

        sext_ln51_128_fu_970_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted8_fu_963_p3),16));

        sext_ln51_129_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted10_fu_986_p3),16));

        sext_ln51_130_fu_1016_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted12_fu_1009_p3),16));

        sext_ln51_131_fu_1039_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted14_fu_1032_p3),16));

        sext_ln51_132_fu_1062_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted16_fu_1055_p3),16));

        sext_ln51_133_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted18_fu_1078_p3),16));

        sext_ln51_134_fu_1108_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted20_fu_1101_p3),16));

        sext_ln51_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted_fu_917_p3),16));

    sext_ln56_257_fu_385_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;
        sext_ln56_257_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_257_fu_385_p0),24));

    sext_ln56_259_fu_445_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;
        sext_ln56_259_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_259_fu_445_p0),24));

    sext_ln56_261_fu_505_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;
        sext_ln56_261_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_261_fu_505_p0),24));

    sext_ln56_263_fu_565_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;
        sext_ln56_263_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_263_fu_565_p0),24));

    sext_ln56_265_fu_625_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;
        sext_ln56_265_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_265_fu_625_p0),24));

    sext_ln56_267_fu_685_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;
        sext_ln56_267_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_267_fu_685_p0),24));

    sext_ln56_269_fu_745_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;
        sext_ln56_269_fu_745_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_269_fu_745_p0),24));

    sext_ln56_271_fu_805_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;
        sext_ln56_271_fu_805_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_271_fu_805_p0),24));

    sext_ln56_273_fu_865_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;
        sext_ln56_273_fu_865_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_273_fu_865_p0),24));

        sext_ln56_384_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_385_fu_329_p3),24));

        sext_ln56_385_fu_905_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_1300),9));

        sext_ln56_386_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_388_fu_389_p3),24));

        sext_ln56_387_fu_928_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_s_reg_1315),9));

        sext_ln56_388_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_391_fu_449_p3),24));

        sext_ln56_389_fu_951_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_127_reg_1330),9));

        sext_ln56_390_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_394_fu_509_p3),24));

        sext_ln56_391_fu_974_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_128_reg_1345),9));

        sext_ln56_392_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_397_fu_569_p3),24));

        sext_ln56_393_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_129_reg_1360),9));

        sext_ln56_394_fu_637_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_400_fu_629_p3),24));

        sext_ln56_395_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_130_reg_1375),9));

        sext_ln56_396_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_403_fu_689_p3),24));

        sext_ln56_397_fu_1043_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_131_reg_1390),9));

        sext_ln56_398_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_406_fu_749_p3),24));

        sext_ln56_399_fu_1066_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_132_reg_1405),9));

        sext_ln56_400_fu_817_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_409_fu_809_p3),24));

        sext_ln56_401_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_133_reg_1420),9));

        sext_ln56_402_fu_877_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_412_fu_869_p3),24));

        sext_ln56_403_fu_1112_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln56_134_reg_1435),9));

    sext_ln56_fu_325_p0 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;
        sext_ln56_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_fu_325_p0),24));

        sext_ln63_fu_1131_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_promoted22_fu_1124_p3),16));

    tmp_385_fu_329_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;
    tmp_385_fu_329_p3 <= (tmp_385_fu_329_p1 & ap_const_lv6_0);
    tmp_387_fu_369_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;
    tmp_387_fu_369_p4 <= tmp_387_fu_369_p1(15 downto 10);
    tmp_388_fu_389_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_8;
    tmp_388_fu_389_p3 <= (tmp_388_fu_389_p1 & ap_const_lv6_0);
    tmp_390_fu_429_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;
    tmp_390_fu_429_p4 <= tmp_390_fu_429_p1(15 downto 10);
    tmp_391_fu_449_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_7;
    tmp_391_fu_449_p3 <= (tmp_391_fu_449_p1 & ap_const_lv6_0);
    tmp_393_fu_489_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;
    tmp_393_fu_489_p4 <= tmp_393_fu_489_p1(15 downto 10);
    tmp_394_fu_509_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_6;
    tmp_394_fu_509_p3 <= (tmp_394_fu_509_p1 & ap_const_lv6_0);
    tmp_396_fu_549_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;
    tmp_396_fu_549_p4 <= tmp_396_fu_549_p1(15 downto 10);
    tmp_397_fu_569_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_5;
    tmp_397_fu_569_p3 <= (tmp_397_fu_569_p1 & ap_const_lv6_0);
    tmp_399_fu_609_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;
    tmp_399_fu_609_p4 <= tmp_399_fu_609_p1(15 downto 10);
    tmp_400_fu_629_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_4;
    tmp_400_fu_629_p3 <= (tmp_400_fu_629_p1 & ap_const_lv6_0);
    tmp_402_fu_669_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;
    tmp_402_fu_669_p4 <= tmp_402_fu_669_p1(15 downto 10);
    tmp_403_fu_689_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_3;
    tmp_403_fu_689_p3 <= (tmp_403_fu_689_p1 & ap_const_lv6_0);
    tmp_405_fu_729_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;
    tmp_405_fu_729_p4 <= tmp_405_fu_729_p1(15 downto 10);
    tmp_406_fu_749_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_2;
    tmp_406_fu_749_p3 <= (tmp_406_fu_749_p1 & ap_const_lv6_0);
    tmp_408_fu_789_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;
    tmp_408_fu_789_p4 <= tmp_408_fu_789_p1(15 downto 10);
    tmp_409_fu_809_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_1;
    tmp_409_fu_809_p3 <= (tmp_409_fu_809_p1 & ap_const_lv6_0);
    tmp_411_fu_849_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;
    tmp_411_fu_849_p4 <= tmp_411_fu_849_p1(15 downto 10);
    tmp_412_fu_869_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials;
    tmp_412_fu_869_p3 <= (tmp_412_fu_869_p1 & ap_const_lv6_0);
    tmp_fu_309_p1 <= void_lif_layer_stream_stream_ap_fixed_12_2_0_3_0_128_potentials_9;
    tmp_fu_309_p4 <= tmp_fu_309_p1(15 downto 10);
    tmp_s_nbreadreq_fu_161_p3 <= (0=>(out1_empty_n), others=>'-');
    zext_ln56_128_fu_931_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_389_reg_1320),9));
    zext_ln56_129_fu_954_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_392_reg_1335),9));
    zext_ln56_130_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_395_reg_1350),9));
    zext_ln56_131_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_398_reg_1365),9));
    zext_ln56_132_fu_1023_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_401_reg_1380),9));
    zext_ln56_133_fu_1046_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_404_reg_1395),9));
    zext_ln56_134_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_407_reg_1410),9));
    zext_ln56_135_fu_1092_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_410_reg_1425),9));
    zext_ln56_136_fu_1115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_413_reg_1440),9));
    zext_ln56_fu_908_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_386_reg_1305),9));
end behav;
